query ($cid: String, $cids: String!, $cid2: String, $cids2: String!) {
  cardById(cardId: $cid) {
    Attack
    def: Defense
    attack(cardID: $cids) {
      Attack
      Defense
    }
  }
  second: cardById(cardId: $cid2) {
    Attack
    def: Defense
    attack(cardID: $cids2) {
      Attack
      Defense
    }
  }
  drawCard {
    Attack
    cardImage {
      bucket
      region
      key
    }
  }
  drawChangeCard {
    ... on EffectCard {
      name
      effectSize
    }
    ... on SpecialCard {
      name
      effect
    }
  }
}
